---
title: "pcoa_resistome_patho"
output: html_document
date: "2024-11-10"
---

```{r}
library(tidyverse)
library(vegan)
library(glue)
library(ggrepel)
library(openxlsx)
library(doParallel)
library(ConQuR)
library(ggtext)
library(scales)
setwd("C:/Users/DAVID 21/OneDrive/Documentos/Mirkoslab/loui/pcoa_resistome")

mw_data<-read_tsv("count_patho_mw_allDS.tsv")
l_data<-read_tsv("count_patho_L_1405DS.tsv")
t_data<-read_tsv("count_patho_wastewatersch_5.2DS.tsv")
last<-read_tsv("count_patho_LIG_P2_3.8DS.tsv")
```

##METADATA
Obtengo y proceso metadata para quedarme con la tabla final que utilizaré
```{r}
met_temp <- data.frame(
  `sample` = c("AR071_1", "AR071_2", "AR071_2", "AR071_2", "AR071_3",
                             "AR072_1", "AR072_1", "AR072_1", "AR072_2", "AR072_2",
                             "AR072_2", "AR072_3", "Mock Community", "Negative control - Human DNA"),
  barcode = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)
)
# Convertir la columna Barcode en el formato barcodeXX
met_temp$barcode <- sprintf("barcode%02d", met_temp$barcode)

# Mostrar el data frame resultante
print(met_temp)

# Crear el segundo data frame con los nuevos datos
additional_data <- data.frame(
  sample = c("AR071_1", "AR071_2", "AR071_3", 
                             "AR072_1", "AR072_2", "AR072_3"),
  place = rep("HMA", 6),  # Columna 'HMA' con valor constante
  date = c("13/02/2024", "13/02/2024", "13/02/2024", 
             "20/02/2024", "20/02/2024", "20/02/2024")
)

# Unir ambos data frames por la columna 'sample_of_extraction'
temp_met <- merge(met_temp, additional_data, by = "sample", all.x = TRUE)


# Crear el tercer data frame con los datos del 2do intento
 el_met<- data.frame(
  sample = c("AR086", "AR093","AR093","AR093", "AR095", 
                             "Mock Community", "Negative control - Human DNA"),
  `date` = c("06/05/2024", "22/05/2024", "22/05/2024", "22/05/2024", "27/05/2024", NA, NA),
  place = c("INSN", "HMA", "HMA", "HMA", "INSN",NA, NA),
  `barcode` = c(24, 23, 22, 21, 20, 19, 18)
)

# Convertir la columna Barcode al formato barcodeXX en el segundo intento
el_met$barcode <- sprintf("barcode%02d", el_met$barcode)

mw_met <- data.frame(
  sample = c("AR070_1", "AR070_1", "AR070_1", "AR070_1",
                             "AR070_2", "AR070_2", "AR070_2",
                             "AR070_3", "AR070_3", "AR070_3", "AR070_3",
                             "Mock Community"),
  barcode = c(1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13)
)

# Añadir las columnas 'HMA' y 'Date' con valores específicos
mw_met$place <- "HMA"
mw_met$date <- "06/02/2024"
mw_met$barcode <- sprintf("barcode%02d", mw_met$barcode)


last_temp <- data.frame(
  sample_id = c("AR083_1", "AR083_2", "AR083_3", "AR113_1", "AR113_2", "AR113_3", "AR074", "Mock Community", "Negative control - Human DNA"),
  barcode = paste0("barcode0",c(1, 2, 3, 4, 5, 6, 7, 8, 9)),
  place = c("HCH", "HCH", "HCH", "INSN", "INSN", "INSN", "HMA", NA, NA),
  date = c("24/04/2024", "24/04/2024", "24/04/2024", "08/07/2024", "08/07/2024", "08/07/2024", "12/03/2024", NA, NA))

el_met<-el_met %>% mutate(folder="L_folder")
temp_met<-temp_met %>% mutate(folder="temporal")
mw_met<-mw_met %>% mutate(folder="MW_P2")
last_temp<-last_temp %>% mutate(folder="LIG_P2")

metadata <- bind_rows(
  "1405Gb" = el_met, 
  final_combined = temp_met, 
  MA_DS9_Crowfoot = mw_met, 
  .id = "source"
) %>%
  select(source, sample, barcode, place, date, folder) %>% 
  rename(sample_id=sample) %>% 
  mutate(sample = str_c(barcode, source, sep = "_")) %>% 
  select(-c(source))
last_temp<-last_temp %>% mutate(sample = paste0(barcode,"_DS_3.8GB"))
metadata<-bind_rows(metadata,last_temp) #%>% 
  #filter(!str_detect(sample_id, "Negative"))
```
##PREPARAR CONTEOS
```{r}
mw_data <- mw_data %>%
  mutate(
    DS = gsub("^[^_]+_", "", Muestra),
    Muestra = gsub("(\\d+)Gb", "MA_DS\\1_Crowfoot", Muestra)
  )
l_data<-l_data %>% 
  mutate(DS="1405Gb")
t_data<-t_data %>% mutate(DS="5.2Gb",Muestra=gsub("_.*$","_final_combined",Muestra))
last<-last %>% mutate(DS="3.8GB") %>% 
    mutate(Muestra = str_replace(Muestra, "barcode07_DS_2.7GB", "barcode07_DS_3.8GB"))
all<-bind_rows(
  L = l_data, 
  MW = mw_data, 
  temporal=t_data,
  lig_p2=last,
  .id = "folder"
) %>% rename(sample=Muestra)
##quedarme con todos los folderes diferentes a MW, y si es MW, que tenga la estructura colocada en sprintf
all_filtered <- all %>%
filter(folder != "MW" | (folder == "MW" & sample %in% sprintf("barcode%02d_MA_DS9_Crowfoot", 1:15))) %>% select(-c(3:5,8:10)) %>%  separate(Feature, into = c("Gen", "Drug_Class"), sep = "_", extra = "merge") %>% 
  separate_rows(Drug_Class, sep = ";") %>% 
   mutate(Drug_Class = str_remove(Drug_Class, "^_+"))
species<-"Acinetobacter baumannii"
all_filtered2<-all_filtered %>% 
  #filter(Drug_Class=="carbapenem") %>% 
  filter(str_detect(Pathogen, species)) %>% 
  group_by(sample,Gen) %>% summarize(conteo=sum(Conteo))
```
HALLAR CPM
```{r}
###AÑADIENDO CONTEOS TOTALES PARA HALLAR CPM
last_seqDS<-read.table("C:/Users/DAVID 21/OneDrive/Documentos/Mirkoslab/loui/abundance/countreadsDS_17sset.tsv.tsv", col.names = c("sample","total"), sep= " ")%>% mutate(sample = gsub(".fastq.gz.*$","", sample)) %>% 
  mutate(total=total/4) %>% slice(1:9)
temporalDS<-read.table("C:/Users/DAVID 21/OneDrive/Documentos/Mirkoslab/loui/abundance/countreadsDS_ch.tsv.txt", col.names = c("sample","total"), sep= " ")  %>% mutate(sample = gsub("DS_.*$","final_combined", sample)) %>% mutate(total=total/4)
#temporal_total<-read_tsv("C:/Users/DAVID 21/OneDrive/Documentos/Mirkoslab/loui/abundance/countreads_ch.tsv.tsv", col_names = c("sample","total"))
mw_total<-read_tsv("C:/Users/DAVID 21/OneDrive/Documentos/Mirkoslab/loui/abundance/countreads_mw.tsv.tsv", col_names = c("sample","total")) 
cpm_norm<-bind_rows(mw_total, temporalDS, last_seqDS) %>% inner_join(all_filtered2,by = "sample") %>% mutate(  # Suma total de conteos por muestra
    cpm = (conteo / total) * 1e6  # Cálculo de CPM
  ) %>%
  select(-c(total,conteo)
)


cpm_matrix<-cpm_norm %>% pivot_wider(names_from = Gen, values_from = cpm, values_fill = 0) %>%
  column_to_rownames("sample") %>%
  as.matrix()


l#og_cpm_matrix <- log(cpm_matrix + 1)
log2_cpm_matrix <- log2(cpm_matrix + 1)
#sqr_cpm_matrix<- sqrt(cpm_matrix)
# Calcula la distancia de Bray-Curtis
#bray_dist <- vegdist(cpm_matrix, method = "bray")
bray_dist <- vegdist(log2_cpm_matrix, method = "bray")
#bray_dist <- vegdist(sqr_cpm_matrix, method = "bray")

# Realiza el PCoA
pcoa <- cmdscale(bray_dist, eig = TRUE, k = 2, add=TRUE)
positions <- pcoa$points #extraigo los vectores
colnames(positions) <- c("pcoa1", "pcoa2") #doy nombres a las coordinates
positions<-positions[order(rownames(positions)), ] #ordeno por nombre de fila
#hallo porcentaje explicado
expl<-(pcoa$eig / sum(pcoa$eig))*100
exp<-format(round(expl[1:2],digits=1),nsmall=1, trim=TRUE)
labs<-c(glue("PCo 1 ({exp[1]}%)"),
        glue("PCo 2 ({exp[2]}%)"))
# Convierto los resultados ordenados de PCoA a tibble y uno con df_variable
# Gráfico PCoA con mejoras y etiquetas de muestras
# Define los colores específicos
palette_colors <- c(
  "HMA_baseline"   = "#2171B5",  # Azul más oscuro
  "HMA_1_week"     = "#4292C6",  # Azul intermedio
  "HMA_2_weeks"    = "#6BAED6",  # Azul más claro
  "HMA_5_weeks"    = "#9ECAE1",  # Azul aún más claro
  "HMA_3_months"   = "#2131B5",  
  "INSN-I"           = "#74C476",
  "INSN-II" = "#A1D99B",
    "HCH"            = "#6A51A3",  # Púrpura oscuro
  "Mock Community" = "#F16913",  # Naranja medio
  "Negative control" = "#CB181D" # Rojo oscuro
)

pc<-positions %>%
  as_tibble(rownames = "sample") %>%
  inner_join(metadata, by = "sample") %>% 
  #filter(!is.na(place)) %>%
  #filter(sample_id!="Mock Community") %>% 
  mutate(
    date = dmy(date)
  ) %>%
  mutate(replicate=gsub("^[^_]+_","",sample_id)) %>% 
  mutate(
    identifier = case_when(sample_id=="Mock Community" ~ "Mock Community",
      place == "HMA" & date == as.Date("2024-02-06") ~ "HMA_baseline",
      place == "HMA" & date == as.Date("2024-02-13") ~ "HMA_1_week",
      place == "HMA" & date == as.Date("2024-02-20") ~ "HMA_2_weeks",
      place == "HMA" & date == as.Date("2024-03-12") ~ "HMA_5_weeks",
      place == "HMA" & date == as.Date("2024-05-22") ~ "HMA_3_months",
      place == "INSN" & date %in% as.Date(c("2024-05-06", "2024-05-27")) ~ "INSN-I",
      place == "INSN" & date == as.Date("2024-07-08") ~ "INSN-II",
      TRUE ~ place
    )) 

# Crear un vector de niveles de 'identifier' ordenados por fecha
ordered_levels <- pc %>%
  select(identifier, date, place) %>%
  distinct() %>%
  mutate(place = factor(place, levels = c("HMA", "INSN", "HCH"))) %>% # Orden específico de 'place'
  arrange(place, date) %>%
  pull(identifier)
ordered_levels <- unique(ordered_levels)
pc <- pc %>%
  mutate(identifier = factor(identifier, levels = ordered_levels))

gg<-pc%>%ggplot(aes(x = pcoa1, y = pcoa2, color = identifier)) +
  geom_point(size = 3, show.legend = TRUE)+
  #stat_ellipse(aes(fill = identifier), geom = "polygon", alpha = 0.2, level = 0.95, show.legend = FALSE)+
  #stat_ellipse(aes(fill = identifier), geom="polygon",alpha=0.2, show.legend = FALSE)+
  #geom_jitter(size = 2.5, stroke = 0.8,width = 0.005, height = 0.005) +  # Coloca geom_point sin size en aes()
  # geom_text_repel(aes(label = identifier), size = 3, max.overlaps = 2, force=2)+#tras
  labs(color = "Sample", x = labs[1], y = labs[2]) +  
  theme_minimal(base_size = 16) +  
  theme(
    axis.title = element_text(size = 16, face = "bold"),  
    axis.text = element_text(size = 14),  
    legend.title = element_text(size = 14),  
    legend.text = element_text(size = 12),  
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5)  
  ) +
  scale_color_manual(values = palette_colors) +  
guides(fill = "none")+
  ggtitle(paste0("PCoA of Resistance Genes in *", species, "*"))+
  theme(plot.title = element_markdown())
#+ xlim(c(-0.105, -0.095))
```
GENES QUE CONTRIBUYEN
```{r}
library(broom)

# Extract PCo1 scores and convert to a dataframe
positions_df <- positions %>%
  as_tibble(rownames = "sample") %>%
  select(sample, pcoa1)
# Convert CPM matrix to a dataframe and reset row names
cpm_df <- as.data.frame(cpm_matrix) %>%
  rownames_to_column("sample")

# Merge PCo1 scores with CPM data
merged_df <- left_join(positions_df, cpm_df, by = "sample")

# Get list of gene names
genes <- colnames(merged_df)[-(1:2)]  # Exclude 'sample' and 'pcoa1' columns

# Compute Spearman correlation between each gene and PCo1 scores
cor_results <- map_dfr(genes, function(gene) {
  cor_test <- cor.test(merged_df[[gene]], merged_df$pcoa1, method = "spearman")
  tibble(
    Gene = gene,
    Correlation = cor_test$estimate,
    P_value = cor_test$p.value
  )
})

# Adjust p-values for multiple testing using Benjamini-Hochberg method
cor_results <- cor_results %>%
  mutate(Adjusted_P_value = p.adjust(P_value, method = "BH"))

# Seleccionar los 10 genes principales con mayor correlación absoluta con PCo1
top_genes <- cor_results %>%
  arrange(desc(abs(Correlation))) %>%
  slice(1:10)
library(ggpubr)

# Formatear la tabla para publicación
top_genes_formatted <- top_genes %>%
  mutate(
    Correlation = round(Correlation, 3),
    P_value = formatC(P_value, format = "e", digits = 2),
    Adjusted_P_value = formatC(Adjusted_P_value, format = "e", digits = 2)
  )

# Display the top 10 genes in a beautiful table
library(knitr)
library(kableExtra)
# Guardar la tabla como HTML
save_kable(
  kable(top_genes_formatted, align = "lccc", caption =
          paste0("Top 10 Genes Influencing PCo1 in PCoA of <i>", species,"<i> (log2)")) %>%
    kable_styling(full_width = FALSE, font_size = 12),
  file = paste0("top_genes_log2_", species, "pcoa.html")
)
#ggsave("top_genes_table.png", tabla_gg, width = 8, height = 4, dpi = 700)

```

BATCH
```{r}
pc_batch<-pc%>% ggplot(aes(x = pcoa1, y = pcoa2, color = folder)) +
  geom_point(size = 3, show.legend = TRUE)+
  #geom_jitter(size = 3, stroke = 0.8,width = 0.005, height = 0.005) +  # Coloca geom_point sin size en aes()
  # geom_text_repel(aes(label = identifier), size = 3, max.overlaps = 2, force=2)+#tras
  labs(color = "Batch", x = labs[1], y = labs[2]) +  
  theme_minimal(base_size = 16) +  
  theme(
    axis.title = element_text(size = 16, face = "bold"),  
    axis.text = element_text(size = 14),  
    legend.title = element_text(size = 14),  
    legend.text = element_text(size = 12),  
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5)  
  ) +
  scale_color_brewer(palette = "Set1") +  
ggtitle(paste0("PCoA of Resistance Genes in *", species, "* by Batch"))+
  theme(title=element_markdown())
```

DATE
```{r}
pc_batch<-positions %>%
  as_tibble(rownames = "sample") %>%
  inner_join(metadata, by = "sample") %>%
  #filter(!is.na(place)) %>%
  #filter(sample_id!="Mock Community") %>% 
  mutate(
    date = dmy(date)
  ) %>%
  mutate(replicate=gsub("^[^_]+_","",sample_id)) %>% 
  mutate(
    identifier = case_when(
      place == "HMA" & date == as.Date("2024-02-06") ~ "HMA_baseline",
      place == "HMA" & date == as.Date("2024-02-13") ~ "HMA_1_week",
      place == "HMA" & date == as.Date("2024-02-20") ~ "HMA_2_weeks",
      place == "HMA" & date == as.Date("2024-03-12") ~ "HMA_5_weeks",
      place == "HMA" & date == as.Date("2024-05-22") ~ "HMA_3_months",
            sample_id=="Mock Community" ~ "Mock Community",
      TRUE ~ place
    )
  ) %>% mutate(date=as.factor(date)) %>% ggplot(aes(x = pcoa1, y = pcoa2, color = date)) +
  geom_point(size = 2.5, show.legend = TRUE)+
  #geom_jitter(size = 2.5, stroke = 0.8,width = 0.005, height = 0.005) +  # Coloca geom_point sin size en aes()
  # geom_text_repel(aes(label = identifier), size = 3, max.overlaps = 2, force=2)+#tras
  labs(color = "Date", x = labs[1], y = labs[2]) +  
  theme_minimal(base_size = 16) +  
  theme(
    axis.title = element_text(size = 16, face = "bold"),  
    axis.text = element_text(size = 14),  
    legend.title = element_text(size = 14),  
    legend.text = element_text(size = 12),  
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5)  
  ) +
  scale_color_brewer(palette = "Set1") +  
ggtitle(paste0("PCoA of Resistance Genes in *", species, "* by Date"))+
  theme(title=element_markdown())
```






